# docker-compose.yml
# Add this top-level entry
version: '3.3'
services:
  redis:
    image: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
  db:
    image: "postgres:12"
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: kondo 
    ports:
      - "5432:5432"
  dl-database-api:
    build:
      context: ./dl-database-api
    ports:
      - "8081:8081"
    expose:
      - 8081
    environment:
      DB_HOST: db
      DB_USERNAME: admin
      DB_PASSWORD: password
      DB_DATABASE: kondo
      WAIT_HOSTS: postgres:5432
    volumes:
      - ./dl-database-api:/dl-database-api
    links:
      - db
    depends_on:
      - db
  dl-github-jobs:
    environment:
      DATABASE_API: 'http://dl-database-api:8081/graphql'
      REDIS_HOST: redis
      PRIVATE_KEY: ${PRIVATE_KEY}
      APP_ID: 30108
      WAIT_HOSTS: dl-database-api:8081
    build:
      context: ./dl-github-jobs
      dockerfile: Dockerfile
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./dl-github-jobs:/home/node/app
    depends_on:
      - dl-database-api
  dl-frontend:
    environment:
      WEB_API: 'http://dl-web-api:8082'
    build:
      context: ./dl-frontend
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
