# docker-compose.yml
# Add this top-level entry
version: '3.3'
services:
  redis:
    image: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
  db:
    image: "postgres:12"
    container_name: "postgres"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: kondo 
    ports:
      - "5432:5432"
  dl-database-api:
    build:
      context: ./dl-database-api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USERNAME: admin
      DB_PASSWORD: password
      DB_DATABASE: kondo
      WAIT_HOSTS: postgres:5432
    volumes:
      - ./dl-database-api:/dl-database-api
    links:
      - db
    depends_on:
      - db
  kondo-github-machine:
    build:
      context: ./kondo-github-machine
      dockerfile: Dockerfile
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./kondo-github-machine:/home/node/app
    expose:
      - "8081"

