# docker-compose.yml
# Add this top-level entry
version: '3.3'
services:
#  redis:
#    image: redislabs/rejson:latest
#    container_name: redis
#    expose:
#      - 6379
#    ports:
#      - "6379:6379"
  kondo-github-machine:
    build:
      context: ./kondo-github-machine
      dockerfile: Dockerfile
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./kondo-github-machine:/home/node/app
    expose:
      - "8081"

